# ---------------------------------------------------------------------------
# VeloxVersion.cmake
#
# Velox Studio's file format is versioned independently from the application
# version. Both are centralised here:
#
#   VELOX_APP_VERSION    semantic application version, including prerelease
#   VLX_FORMAT_VERSION   on-disk .vlx document container version
#   VELOX_PLUGIN_API_VERSION  plugin ABI version
#
# velox_generate_version_header(<target>) writes a generated header exposing
# these constants, plus the git revision and build type, to C++.
# ---------------------------------------------------------------------------

include_guard(GLOBAL)

set(VLX_FORMAT_VERSION      1       CACHE INTERNAL "Version of the .vlx document container format")
set(VELOX_PLUGIN_API_VERSION 1      CACHE INTERNAL "Plugin API version")

# Discover the current git revision so build info dialogs and crash logs can
# identify exactly which commit produced a binary.
function(velox_resolve_git_revision out_var)
    set(_rev "unknown")
    find_package(Git QUIET)
    if (GIT_FOUND AND EXISTS "${CMAKE_SOURCE_DIR}/.git")
        execute_process(
            COMMAND "${GIT_EXECUTABLE}" rev-parse --short=12 HEAD
            WORKING_DIRECTORY "${CMAKE_SOURCE_DIR}"
            OUTPUT_VARIABLE _out
            ERROR_QUIET
            OUTPUT_STRIP_TRAILING_WHITESPACE
            RESULT_VARIABLE _rc
        )
        if (_rc EQUAL 0 AND _out)
            set(_rev "${_out}")
            execute_process(
                COMMAND "${GIT_EXECUTABLE}" status --porcelain --untracked-files=no
                WORKING_DIRECTORY "${CMAKE_SOURCE_DIR}"
                OUTPUT_VARIABLE _dirty
                ERROR_QUIET
                OUTPUT_STRIP_TRAILING_WHITESPACE
            )
            if (_dirty)
                set(_rev "${_rev}-dirty")
            endif()
        endif()
    endif()
    set(${out_var} "${_rev}" PARENT_SCOPE)
endfunction()

# Writes Version.generated.h into the target's binary directory and registers
# it on the target. The header is regenerated whenever the git revision changes.
function(velox_generate_version_header target)
    velox_resolve_git_revision(_git_rev)

    string(REGEX REPLACE "^${PROJECT_VERSION}(-)?" "" VELOX_APP_VERSION_PRERELEASE
        "${VELOX_APP_VERSION}")
    string(TIMESTAMP _build_date "%Y-%m-%d" UTC)

    set(_out_dir "${CMAKE_CURRENT_BINARY_DIR}/generated")
    set(_header   "${_out_dir}/velox/Version.generated.h")
    file(MAKE_DIRECTORY "${_out_dir}/velox")

    # Only rewrite on change so incremental builds are not invalidated.
    set(_content
"// ---------------------------------------------------------------------------
// Generated by cmake/VeloxVersion.cmake - do not edit.
// ---------------------------------------------------------------------------
#pragma once

#define VELOX_VERSION_MAJOR        ${PROJECT_VERSION_MAJOR}
#define VELOX_VERSION_MINOR        ${PROJECT_VERSION_MINOR}
#define VELOX_VERSION_PATCH        ${PROJECT_VERSION_PATCH}
#define VELOX_VERSION_STRING       \"${VELOX_APP_VERSION}\"
#define VELOX_VERSION_PRERELEASE   \"${VELOX_APP_VERSION_PRERELEASE}\"

#define VELOX_VLX_FORMAT_VERSION   ${VLX_FORMAT_VERSION}
#define VELOX_PLUGIN_API_VERSION   ${VELOX_PLUGIN_API_VERSION}

#define VELOX_BUILD_REVISION       \"${_git_rev}\"
#define VELOX_BUILD_DATE           \"${_build_date}\"
#define VELOX_BUILD_CONFIG         \"${CMAKE_BUILD_TYPE}\"
#define VELOX_BUILD_ARCH           \"${CMAKE_SYSTEM_PROCESSOR}\"
")

    if (EXISTS "${_header}")
        file(READ "${_header}" _existing)
    else()
        set(_existing "")
    endif()

    if (NOT _existing STREQUAL _content)
        file(WRITE "${_header}" "${_content}")
    endif()

    target_include_directories(${target} PUBLIC "${_out_dir}")
endfunction()